# Generated by Django 4.2 on 2023-04-13 19:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('nickname', models.CharField(blank=True, default='Anonymous', max_length=125, null=True)),
                ('anonymous', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_media', verbose_name='Blog image')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='userprofile.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='StoryReactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.PositiveIntegerField(choices=[(1, '&#128512'), (2, '&#128513'), (3, '&#128518'), (4, '&#128517'), (5, '&#129315'), (6, '&#128579'), (7, '&#128521'), (8, '&#128522'), (9, '&#128519'), (10, '&#129392'), (11, '&#128525'), (12, '&#129321'), (13, '&#128536'), (14, '&#129322'), (15, '&#128529'), (16, '&#128530'), (17, '&#128556'), (18, '&#129319'), (19, '&#129327'), (20, '&#128560'), (21, '&#129324'), (22, '&#128128'), (23, '&#128570'), (24, '&#128076'), (25, '&#128075'), (26, '&#128077'), (27, '&#128074'), (28, '&#129460'), (29, '&#128064'), (30, '&#129461'), (31, '&#128170')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stories.story')),
            ],
        ),
    ]
