# Generated by Django 4.2 on 2023-04-13 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
        ('stories', '0002_story_story_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='name',
        ),
        migrations.AddField(
            model_name='story',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='userprofile.userprofile'),
        ),
    ]
