# Generated by Django 4.2 on 2023-04-15 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0005_alter_story_username'),
        ('stories', '0005_story_dislikes_story_likes_delete_storyreactions'),
    ]

    operations = [
    ]
