# Generated by Django 4.2 on 2023-04-15 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0006_alter_story_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyreactions',
            name='story',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='stories.story'),
        ),
    ]
