# Generated by Django 4.2 on 2023-04-15 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0006_merge_20230415_1203'),
        ('stories', '0008_delete_storyreactions'),
    ]

    operations = [
    ]
