# Generated by Django 4.2 on 2023-04-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='First_name',
            field=models.CharField(help_text='First name', max_length=25),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Last_name',
            field=models.CharField(help_text='Last name', max_length=25),
        ),
    ]
